# This workflow will install Python dependencies and run tests
name: EveMarketPython
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies and 
      run: |
        python -m pip install --upgrade pip
        cd src
        pip install -e ".[test]"
        pytest ../tests/     
